syntax = "proto3";

package user;

option go_package = "github.com/mohamed/microservices/user-service/proto";


// ============================
// User Service
// ============================

service UserService {
    rpc GetAllUsers(Empty) returns (UserList);
    rpc GetUserById(UserIdRequest) returns (User);
    rpc CreateUser(CreateUserRequest) returns (User);
    rpc DeleteUser(UserIdRequest) returns (Empty);
}

// --- Employee Messages ---

message Empty {}

message User {
    int32 id   = 1;
    string name = 2;
    string email = 3;
}

message UserIdRequest {
    int32 id = 1;
}

message CreateUserRequest {
    string name = 1;
    string email = 2;
}

message UserList {
  repeated User users = 1;
}